name: connectycube_flutter_call_kit
description: A Flutter plugin for displaying call screen when app in background or terminated.
version: 2.1.0
homepage: https://github.com/ConnectyCube/connectycube-flutter-call-kit
issue_tracker: https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.connectycube.flutter.connectycube_flutter_call_kit
        pluginClass: ConnectycubeFlutterCallKitPlugin
      ios:
        pluginClass: ConnectycubeFlutterCallKitPlugin